[general]
chain = "dev"
log4rs_config = "stegos-log4rs.toml"
prometheus_endpoint = "127.0.0.1:9893"
api_endpoint = "127.0.0.1:3147"
data_dir = "testing/node03"
force_check = true

[network]
bind_ip = "127.0.0.1"
bind_port = 10057
advertise_local_ips = false
hashcash_nbits = 4
seed_nodes = [
    "/ip4/127.0.0.1/tcp/10055",
    "/ip4/127.0.0.1/tcp/10056",
    "/ip4/127.0.0.1/tcp/10058",
]
advertised_addresses = [
    "/ip4/127.0.0.1/tcp/10057",
]